version: '3.8'

services:
  # Frontend (Nginx)
  nginx:
    container_name: nginx-server
    build:
      context: ./gift-tok-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx yapılandırması
      - ./gift-tok-front:/usr/share/nginx/html  # Host makinedeki frontend dosyaları konteynere bağlanıyor
    networks:
      - app-network

  # Backend (Java tətbiqi)
  gift-tok-back:
    container_name: gift-tok-back
    build:
      context: ./gift-tok-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db  # gift-tok-back PostgreSQL-ə asılıdır
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: gift_tok_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # PostgreSQL (Verilənlər bazası)
  db:
    image: postgres:16
    container_name: gift-tok-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gift_tok_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-data:
  # frontend-static volume kaldırıldı, çünkü bind mount kullanıyoruz.

networks:
  app-network:
    driver: bridge
