version: '3.8'

services:
  # PostgreSQL veritabanı
  gift-tok-back-db:
    container_name: gift-tok-back-db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

  # Backend (Java uygulaması)
  gift-tok-back:
    stdin_open: true
    tty: true
    container_name: gift-tok-back
    build:
      context: ./gift-tok-back  # Backend dizini
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gift-tok-back-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - gift-tok-back-db
    networks:
      - app-network

  # Frontend (Nginx)
  nginx:
    container_name: nginx-server
    build:
      context: ./gift-tok-front  # Frontend dizini
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Frontend Nginx portu
    depends_on:
      - gift-tok-back  # Nginx, backend başlamadan başlatılmayacak
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfigürasyon dosyası
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
